#!/usr/bin/env bash
#
# Generated by: https://openapi-generator.tech
#

dotnet restore src/Petstore/ && \
    dotnet build src/Petstore/ && \
    echo "Now, run the following to start the project: dotnet run -p src/Petstore/Petstore.csproj --launch-profile web"
