/*
 * Swagger Petstore - OpenAPI 3.1
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * API version: 1.0.12
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstore

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

type StoreAPI struct {
	Store Store
}

// Delete /api/v3/store/order/:orderId
// Delete purchase order by identifier.
func (api *StoreAPI) DeleteOrder(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	id, ok := parseInt64Param(c, "orderId")
	if !ok {
		return
	}
	deleted, err := api.Store.DeleteOrder(c.Request.Context(), id)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	if !deleted {
		writeNotFound(c, fmt.Sprintf("order %d not found", id))
		return
	}
	c.Status(http.StatusOK)
}

// Get /api/v3/store/inventory
// Returns pet inventories by status.
func (api *StoreAPI) GetInventory(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	inventory, err := api.Store.Inventory(c.Request.Context())
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, inventory)
}

// Get /api/v3/store/order/:orderId
// Find purchase order by identifier.
func (api *StoreAPI) GetOrderById(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	id, ok := parseInt64Param(c, "orderId")
	if !ok {
		return
	}
	order, err := api.Store.GetOrderByID(c.Request.Context(), id)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, order)
}

// Post /api/v3/store/order
// Place an order for a pet.
func (api *StoreAPI) PlaceOrder(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	var order Order
	if !bindJSON(c, &order) {
		return
	}
	if !validOrderStatus(order.Status) {
		writeError(c, http.StatusBadRequest, "invalid_status", "order status must be placed, approved, or delivered")
		return
	}
	created, err := api.Store.CreateOrder(c.Request.Context(), order)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, created)
}
