/*
 * Swagger Petstore - OpenAPI 3.1
 *
 * This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
 *
 * API version: 1.0.12
 * Contact: apiteam@swagger.io
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package petstore

import (
	"fmt"
	"net/http"

	"github.com/gin-gonic/gin"
)

type UserAPI struct {
	Store Store
}

// Post /api/v3/user
// Create user.
func (api *UserAPI) CreateUser(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	var user User
	if !bindJSON(c, &user) {
		return
	}
	created, err := api.Store.CreateUser(c.Request.Context(), user)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, created)
}

// Post /api/v3/user/createWithList
// Creates list of users with given input array.
func (api *UserAPI) CreateUsersWithListInput(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	var users []User
	if !bindJSON(c, &users) {
		return
	}
	created, err := api.Store.CreateUsers(c.Request.Context(), users)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, created)
}

// Delete /api/v3/user/:username
// Delete user.
func (api *UserAPI) DeleteUser(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	username := c.Param("username")
	if username == "" {
		writeError(c, http.StatusBadRequest, "invalid_username", "username is required")
		return
	}
	deleted, err := api.Store.DeleteUser(c.Request.Context(), username)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	if !deleted {
		writeNotFound(c, fmt.Sprintf("user %s not found", username))
		return
	}
	c.Status(http.StatusOK)
}

// Get /api/v3/user/:username
// Get user by user name.
func (api *UserAPI) GetUserByName(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	username := c.Param("username")
	if username == "" {
		writeError(c, http.StatusBadRequest, "invalid_username", "username is required")
		return
	}
	user, err := api.Store.GetUserByUsername(c.Request.Context(), username)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	c.JSON(http.StatusOK, user)
}

// Get /api/v3/user/login
// Logs user into the system.
func (api *UserAPI) LoginUser(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	username := c.Query("username")
	password := c.Query("password")
	if username == "" || password == "" {
		writeError(c, http.StatusBadRequest, "invalid_credentials", "username and password are required")
		return
	}
	ok, err := api.Store.AuthenticateUser(c.Request.Context(), username, password)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	if !ok {
		writeError(c, http.StatusBadRequest, "invalid_credentials", "invalid username or password")
		return
	}
	setLoginHeaders(c)
	c.String(http.StatusOK, "logged in user session: %s", username)
}

// Get /api/v3/user/logout
// Logs out current logged in user session.
func (api *UserAPI) LogoutUser(c *gin.Context) {
	c.Status(http.StatusOK)
}

// Put /api/v3/user/:username
// Update user.
func (api *UserAPI) UpdateUser(c *gin.Context) {
	if !requireStore(c, api.Store) {
		return
	}
	username := c.Param("username")
	if username == "" {
		writeError(c, http.StatusBadRequest, "invalid_username", "username is required")
		return
	}
	var user User
	if !bindJSON(c, &user) {
		return
	}
	updated, err := api.Store.UpdateUser(c.Request.Context(), username, user)
	if err != nil {
		handleStoreError(c, err)
		return
	}
	if !updated {
		writeNotFound(c, fmt.Sprintf("user %s not found", username))
		return
	}
	c.Status(http.StatusOK)
}
