// Data access layer for the benchmark viewer.
// All fetch calls hit /data/ which is served from public/data/ (generated by build-data.mjs).

let _index = null;

export async function loadIndex() {
  if (_index) return _index;
  const res = await fetch("./data/index.json");
  if (!res.ok) throw new Error(`Failed to load index.json: ${res.status}`);
  _index = await res.json();
  return _index;
}

const _runCache = {};

export async function loadRun(runId) {
  if (_runCache[runId]) return _runCache[runId];
  const res = await fetch(`./data/runs/${runId}.json`);
  if (!res.ok) throw new Error(`Failed to load run ${runId}: ${res.status}`);
  _runCache[runId] = await res.json();
  return _runCache[runId];
}

// Group runs from index by stack label, sorted by label.
export function groupByStack(runs) {
  const map = {};
  for (const r of runs) {
    const key = r.label;
    if (!map[key]) map[key] = [];
    map[key].push(r);
  }
  // Sort runs within each stack by timestamp descending
  for (const k of Object.keys(map)) {
    map[k].sort((a, b) => (b.timestamp > a.timestamp ? 1 : -1));
  }
  return map;
}

// Stable color palette for up to 4 comparison series
export const SERIES_COLORS = [
  "#6366f1", // indigo
  "#22c55e", // green
  "#f59e0b", // amber
  "#ec4899", // pink
];

export function seriesColor(idx) {
  return SERIES_COLORS[idx % SERIES_COLORS.length];
}

// Value formatter — mirrors report.py fmt()
export function fmt(val, decimals = 2) {
  if (val == null || val === undefined) return "—";
  if (typeof val === "number") return val.toFixed(decimals);
  return String(val);
}

export function fmtMs(val) {
  return val == null ? "—" : `${val.toFixed(1)} ms`;
}

export function fmtPct(val) {
  return val == null ? "—" : `${(val * 100).toFixed(2)}%`;
}

export function fmtRps(val) {
  return val == null ? "—" : val.toFixed(1);
}

// Unique sorted durations available for a given set of runs (e.g. "15s", "30s", "60s")
export function durationsForRuns(runs) {
  const seen = new Set();
  for (const r of runs) if (r.duration) seen.add(r.duration);
  // Sort numerically by the numeric prefix (15s < 30s < 60s < 120s)
  return [...seen].sort((a, b) => parseInt(a) - parseInt(b));
}

// Human-friendly run label shown in the final (run) dropdown.
// Duration is shown in the parent dropdown now, so we omit it here.
export function runLabel(run) {
  const ts = run.timestamp.replace(/T(\d{2})(\d{2})(\d{2})Z/, " $1:$2:$3Z");
  return `${run.variant} · ${ts} (${run.vus ?? "?"}VU)`;
}
