/**
* Swagger Petstore - OpenAPI 3.1
* This is a sample Pet Store Server based on the OpenAPI 3.1 specification.  You can find out more about Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach! You can now help us improve the API whether it's by making changes to the definition itself or to the code. That way, with time, we can improve the API in general, and expose some of the new features in OAS3.  Some useful links: - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore) - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
*
* The version of the OpenAPI document: 1.0.12
* Contact: apiteam@swagger.io
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.example.petstore

import io.ktor.resources.*
import kotlinx.serialization.*
import com.example.petstore.models.*

object Paths {
    /**
     * Add a new pet to the store.
     * Add a new pet to the store.
     * @param pet Create a new pet in the store 
     */
    @Resource("/pet") class addPet()

    /**
     * Deletes a pet.
     * delete a pet.
     * @param petId Pet id to delete 
     * @param apiKey  (optional)
     */
    @Resource("/pet/{petId}") class deletePet(val petId: kotlin.Long)

    /**
     * Finds Pets by status.
     * Multiple status values can be provided with comma separated strings.
     * @param status Status values that need to be considered for filter (optional, default to available)
     */
    @Resource("/pet/findByStatus") class findPetsByStatus(val status: kotlin.String? = null)

    /**
     * Finds Pets by tags.
     * Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
     * @param tags Tags to filter by (optional)
     */
    @Resource("/pet/findByTags") class findPetsByTags(val tags: kotlin.collections.List<kotlin.String>? = null)

    /**
     * Find pet by identifier.
     * Returns a single pet.
     * @param petId ID of pet to return 
     */
    @Resource("/pet/{petId}") class getPetById(val petId: kotlin.Long)

    /**
     * Update an existing pet.
     * Update an existing pet by Id.
     * @param pet Update an existent pet in the store 
     */
    @Resource("/pet") class updatePet()

    /**
     * Updates a pet in the store with form data.
     * update a pet via the form data.
     * @param petId ID of pet that needs to be updated 
     * @param name Name of pet that needs to be updated (optional)
     * @param status Status of pet that needs to be updated (optional)
     */
    @Resource("/pet/{petId}") class updatePetWithForm(val petId: kotlin.Long, val name: kotlin.String? = null, val status: kotlin.String? = null)

    /**
     * Uploads an image.
     * Upload an image of pet.
     * @param petId ID of pet to update 
     * @param additionalMetadata Additional Metadata (optional)
     * @param body  (optional)
     */
    @Resource("/pet/{petId}/uploadImage") class uploadFile(val petId: kotlin.Long, val additionalMetadata: kotlin.String? = null)

    /**
     * Delete purchase order by identifier.
     * For valid response try integer IDs with value &lt; 1000. Anything above 1000 or non-integers will generate API errors.
     * @param orderId ID of the order that needs to be deleted 
     */
    @Resource("/store/order/{orderId}") class deleteOrder(val orderId: kotlin.Long)

    /**
     * Returns pet inventories by status.
     * Returns a map of status codes to quantities.
     */
    @Resource("/store/inventory") class getInventory

    /**
     * Find purchase order by identifier.
     * For valid response try integer IDs with value &lt;&#x3D; 5 or &gt; 10. Other values will generate exceptions.
     * @param orderId ID of order that needs to be fetched 
     */
    @Resource("/store/order/{orderId}") class getOrderById(val orderId: kotlin.Long)

    /**
     * Place an order for a pet.
     * Place a new order in the store.
     * @param order  (optional)
     */
    @Resource("/store/order") class placeOrder()

    /**
     * Create user.
     * This can only be done by the logged in user.
     * @param user Created user object (optional)
     */
    @Resource("/user") class createUser()

    /**
     * Creates list of users with given input array.
     * Creates list of users with given input array.
     * @param user  (optional)
     */
    @Resource("/user/createWithList") class createUsersWithListInput()

    /**
     * Delete user.
     * This can only be done by the logged in user.
     * @param username The name that needs to be deleted 
     */
    @Resource("/user/{username}") class deleteUser(val username: kotlin.String)

    /**
     * Get user by user name.
     * Get user details based on username.
     * @param username The name that needs to be fetched. Use user1 for testing 
     */
    @Resource("/user/{username}") class getUserByName(val username: kotlin.String)

    /**
     * Logs user into the system.
     * log user into the system.
     * @param username The user name for login (optional)
     * @param password The password for login in clear text (optional)
     */
    @Resource("/user/login") class loginUser(val username: kotlin.String? = null, val password: kotlin.String? = null)

    /**
     * Logs out current logged in user session.
     * Log user out of system.
     */
    @Resource("/user/logout") class logoutUser

    /**
     * Update user.
     * This can only be done by the logged in user.
     * @param username name that need to be deleted 
     * @param user Update an existent user in the store (optional)
     */
    @Resource("/user/{username}") class updateUser(val username: kotlin.String)

}
