source 'https://rubygems.org'

gem 'rails', '~> 8.1'
gem 'puma', '>= 5.0'
gem 'pg', '~> 1.5'

group :development, :test do
  gem 'debug', platforms: %i[mri mswin mswin64 mingw x64_mingw]
  gem 'rspec', '~> 3.13'
  gem 'mutant-rspec', require: false
end
