/*
 * Swagger Petstore - OpenAPI 3.1
 *
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Newtonsoft.Json;
using Petstore.Attributes;
using Petstore.Models;
using Petstore.Repositories;

namespace Petstore.Controllers
{
    [ApiController]
    public class PetApiController : ControllerBase
    {
        private readonly IPetstoreRepository _repo;

        public PetApiController(IPetstoreRepository repo)
        {
            _repo = repo;
        }

        /// <summary>Add a new pet to the store.</summary>
        [HttpPost]
        [Route("/api/v3/pet")]
        [Consumes("application/json", "application/xml", "application/x-www-form-urlencoded")]
        [ValidateModelState]
        [SwaggerOperation("AddPet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Pet), description: "Successful operation")]
        public virtual async Task<IActionResult> AddPet([FromBody] Pet pet)
        {
            var result = await _repo.AddPet(pet);
            return new ObjectResult(result);
        }

        /// <summary>Deletes a pet.</summary>
        [HttpDelete]
        [Route("/api/v3/pet/{petId}")]
        [ValidateModelState]
        [SwaggerOperation("DeletePet")]
        public virtual async Task<IActionResult> DeletePet(
            [FromRoute(Name = "petId")][Required] long petId,
            [FromHeader(Name = "api_key")] string apiKey)
        {
            var found = await _repo.DeletePet(petId);
            return found ? StatusCode(200) : NotFound();
        }

        /// <summary>Finds Pets by status.</summary>
        [HttpGet]
        [Route("/api/v3/pet/findByStatus")]
        [ValidateModelState]
        [SwaggerOperation("FindPetsByStatus")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Pet>), description: "successful operation")]
        public virtual async Task<IActionResult> FindPetsByStatus([FromQuery(Name = "status")] string status)
        {
            var result = await _repo.FindPetsByStatus(status);
            return new ObjectResult(result);
        }

        /// <summary>Finds Pets by tags.</summary>
        [HttpGet]
        [Route("/api/v3/pet/findByTags")]
        [ValidateModelState]
        [SwaggerOperation("FindPetsByTags")]
        [SwaggerResponse(statusCode: 200, type: typeof(List<Pet>), description: "successful operation")]
        public virtual async Task<IActionResult> FindPetsByTags([FromQuery(Name = "tags")] List<string> tags)
        {
            var result = await _repo.FindPetsByTags(tags);
            return new ObjectResult(result);
        }

        /// <summary>Find pet by identifier.</summary>
        [HttpGet]
        [Route("/api/v3/pet/{petId}")]
        [Authorize(Policy = "api_key")]
        [ValidateModelState]
        [SwaggerOperation("GetPetById")]
        [SwaggerResponse(statusCode: 200, type: typeof(Pet), description: "successful operation")]
        public virtual async Task<IActionResult> GetPetById([FromRoute(Name = "petId")][Required] long petId)
        {
            var pet = await _repo.GetPetById(petId);
            return pet == null ? NotFound() : new ObjectResult(pet);
        }

        /// <summary>Update an existing pet.</summary>
        [HttpPut]
        [Route("/api/v3/pet")]
        [Consumes("application/json", "application/xml", "application/x-www-form-urlencoded")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Pet), description: "Successful operation")]
        public virtual async Task<IActionResult> UpdatePet([FromBody] Pet pet)
        {
            var result = await _repo.UpdatePet(pet);
            return result == null ? NotFound() : new ObjectResult(result);
        }

        /// <summary>Updates a pet in the store with form data.</summary>
        [HttpPost]
        [Route("/api/v3/pet/{petId}")]
        [ValidateModelState]
        [SwaggerOperation("UpdatePetWithForm")]
        public virtual async Task<IActionResult> UpdatePetWithForm(
            [FromRoute(Name = "petId")][Required] long petId,
            [FromQuery(Name = "name")] string name,
            [FromQuery(Name = "status")] string status)
        {
            var found = await _repo.UpdatePetWithForm(petId, name, status);
            return found ? StatusCode(200) : NotFound();
        }

        /// <summary>Uploads an image.</summary>
        [HttpPost]
        [Route("/api/v3/pet/{petId}/uploadImage")]
        [Consumes("application/octet-stream")]
        [ValidateModelState]
        [SwaggerOperation("UploadFile")]
        [SwaggerResponse(statusCode: 200, type: typeof(ApiResponse), description: "successful operation")]
        public virtual async Task<IActionResult> UploadFile(
            [FromRoute(Name = "petId")][Required] long petId,
            [FromQuery(Name = "additionalMetadata")] string additionalMetadata,
            [FromBody] System.IO.Stream body)
        {
            var result = await _repo.UploadFile(petId, additionalMetadata, body);
            return result == null ? NotFound() : new ObjectResult(result);
        }
    }
}
