/*
 * Swagger Petstore - OpenAPI 3.1
 *
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Petstore.Attributes;
using Petstore.Models;
using Petstore.Repositories;

namespace Petstore.Controllers
{
    [ApiController]
    public class StoreApiController : ControllerBase
    {
        private readonly IPetstoreRepository _repo;

        public StoreApiController(IPetstoreRepository repo)
        {
            _repo = repo;
        }

        /// <summary>Delete purchase order by identifier.</summary>
        [HttpDelete]
        [Route("/api/v3/store/order/{orderId}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteOrder")]
        public virtual async Task<IActionResult> DeleteOrder([FromRoute(Name = "orderId")][Required] long orderId)
        {
            var found = await _repo.DeleteOrder(orderId);
            return found ? StatusCode(200) : NotFound();
        }

        /// <summary>Returns pet inventories by status.</summary>
        [HttpGet]
        [Route("/api/v3/store/inventory")]
        [Authorize(Policy = "api_key")]
        [ValidateModelState]
        [SwaggerOperation("GetInventory")]
        [SwaggerResponse(statusCode: 200, type: typeof(Dictionary<string, int>), description: "successful operation")]
        public virtual async Task<IActionResult> GetInventory()
        {
            var result = await _repo.GetInventory();
            return new ObjectResult(result);
        }

        /// <summary>Find purchase order by identifier.</summary>
        [HttpGet]
        [Route("/api/v3/store/order/{orderId}")]
        [ValidateModelState]
        [SwaggerOperation("GetOrderById")]
        [SwaggerResponse(statusCode: 200, type: typeof(Order), description: "successful operation")]
        public virtual async Task<IActionResult> GetOrderById([FromRoute(Name = "orderId")][Required] long orderId)
        {
            var order = await _repo.GetOrderById(orderId);
            return order == null ? NotFound() : new ObjectResult(order);
        }

        /// <summary>Place an order for a pet.</summary>
        [HttpPost]
        [Route("/api/v3/store/order")]
        [Consumes("application/json", "application/xml", "application/x-www-form-urlencoded")]
        [ValidateModelState]
        [SwaggerOperation("PlaceOrder")]
        [SwaggerResponse(statusCode: 200, type: typeof(Order), description: "successful operation")]
        public virtual async Task<IActionResult> PlaceOrder([FromBody] Order order)
        {
            var result = await _repo.PlaceOrder(order);
            return new ObjectResult(result);
        }
    }
}
