/*
 * Swagger Petstore - OpenAPI 3.1
 *
 * Generated by: https://openapi-generator.tech
 */

using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Petstore.Attributes;
using Petstore.Models;
using Petstore.Repositories;

namespace Petstore.Controllers
{
    [ApiController]
    public class UserApiController : ControllerBase
    {
        private readonly IPetstoreRepository _repo;

        public UserApiController(IPetstoreRepository repo)
        {
            _repo = repo;
        }

        /// <summary>Create user.</summary>
        [HttpPost]
        [Route("/api/v3/user")]
        [Consumes("application/json", "application/xml", "application/x-www-form-urlencoded")]
        [ValidateModelState]
        [SwaggerOperation("CreateUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(User), description: "Successful operation")]
        public virtual async Task<IActionResult> CreateUser([FromBody] User user)
        {
            var result = await _repo.CreateUser(user);
            return new ObjectResult(result);
        }

        /// <summary>Creates list of users with given input array.</summary>
        [HttpPost]
        [Route("/api/v3/user/createWithList")]
        [Consumes("application/json")]
        [ValidateModelState]
        [SwaggerOperation("CreateUsersWithListInput")]
        [SwaggerResponse(statusCode: 200, type: typeof(User), description: "Successful operation")]
        public virtual async Task<IActionResult> CreateUsersWithListInput([FromBody] List<User> user)
        {
            var result = await _repo.CreateUsersWithListInput(user);
            return result == null ? StatusCode(200) : new ObjectResult(result);
        }

        /// <summary>Delete user.</summary>
        [HttpDelete]
        [Route("/api/v3/user/{username}")]
        [ValidateModelState]
        [SwaggerOperation("DeleteUser")]
        public virtual async Task<IActionResult> DeleteUser([FromRoute(Name = "username")][Required] string username)
        {
            var found = await _repo.DeleteUser(username);
            return found ? StatusCode(200) : NotFound();
        }

        /// <summary>Get user by user name.</summary>
        [HttpGet]
        [Route("/api/v3/user/{username}")]
        [ValidateModelState]
        [SwaggerOperation("GetUserByName")]
        [SwaggerResponse(statusCode: 200, type: typeof(User), description: "successful operation")]
        public virtual async Task<IActionResult> GetUserByName([FromRoute(Name = "username")][Required] string username)
        {
            var user = await _repo.GetUserByName(username);
            return user == null ? NotFound() : new ObjectResult(user);
        }

        /// <summary>Logs user into the system.</summary>
        [HttpGet]
        [Route("/api/v3/user/login")]
        [ValidateModelState]
        [SwaggerOperation("LoginUser")]
        [SwaggerResponse(statusCode: 200, type: typeof(string), description: "successful operation")]
        public virtual async Task<IActionResult> LoginUser(
            [FromQuery(Name = "username")] string username,
            [FromQuery(Name = "password")] string password)
        {
            var token = await _repo.LoginUser(username, password);
            return new ObjectResult(token);
        }

        /// <summary>Logs out current logged in user session.</summary>
        [HttpGet]
        [Route("/api/v3/user/logout")]
        [ValidateModelState]
        [SwaggerOperation("LogoutUser")]
        public virtual async Task<IActionResult> LogoutUser()
        {
            await _repo.LogoutUser();
            return StatusCode(200);
        }

        /// <summary>Update user.</summary>
        [HttpPut]
        [Route("/api/v3/user/{username}")]
        [Consumes("application/json", "application/xml", "application/x-www-form-urlencoded")]
        [ValidateModelState]
        [SwaggerOperation("UpdateUser")]
        public virtual async Task<IActionResult> UpdateUser(
            [FromRoute(Name = "username")][Required] string username,
            [FromBody] User user)
        {
            await _repo.UpdateUser(username, user);
            return StatusCode(200);
        }
    }
}
