FROM golang:1.23 AS deps
WORKDIR /go/src
COPY go.mod go.sum ./
RUN go mod download

FROM deps AS build
COPY . .
RUN CGO_ENABLED=0 go build -ldflags="-w -s" -trimpath -o petstore .

FROM scratch
COPY --from=build /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/
COPY --from=build /go/src/petstore /petstore
USER 65534:65534
ENV FIBER_DISABLE_REQUEST_LOGGING=true GOMEMLIMIT=460MiB DB_MAX_OPEN_CONNS=200 DB_MAX_IDLE_CONNS=50
EXPOSE 8080/tcp
ENTRYPOINT ["/petstore"]
